### ISSUE TITLE
FYI cucumber-protractor does output json

### ISSUE THREAD

**Issue by leegee** [mrooding/gulp-protractor-cucumber-html-report#12]
> If you're using Protractor in combination with CucumberJS there currently is no way to save the CucumberJS JSON output to a file.

The ticket to which that text links is closed as 'done'.

Certainly using the excellent `protractor-cucumber`, adding `resultJsonOutputFile` to the config does produce JSON as expected.

**Comment by leegee** [comment]
...but it's JSON does not seem compatible:

```
[
  {
    "description": "Log in and get initial state.",
    "assertions": [
      {
        "passed": true
      },
      {
        "passed": true
      }
    ],
    "duration": 2872582695
  }
]
```

**Comment by djom202** [comment]
I have the same issue, how to configure protractor to export a json compatible with this plugin?
