### ISSUE TITLE
After hook's `scenario.attach` rendered as 'After undefined'

### ISSUE THREAD

**Issue by leegee** [mrooding/gulp-protractor-cucumber-html-report#13]
From the `cucumberjs` README, I used these in an 'after scenario' hook:

```
        scenario.attach('Some text');
        this.After(function (scenario) {
            scenario.attach('{"name": "some JSON"}', 'application/json');
        });
```

The otherwise lovely HTML report renders 'After undefined'.

![fireshot capture 28 - - http___localhost_3000_reports_e2e_e2e-report html](https://cloud.githubusercontent.com/assets/512816/14853089/f6c314fc-0c81-11e6-912b-6ab514415609.png)
[e2e-report.zip](https://github.com/mrooding/gulp-protractor-cucumber-html-report/files/238668/e2e-report.zip)

**Comment by danyc** [comment]
Fixed in 0.1.2
