### ISSUE TITLE
Add sample screenshot to readme

### ISSUE THREAD

**Issue by mucsi96** [mrooding/gulp-protractor-cucumber-html-report#14]
It would be very useful to add a sample screenshot to readme.md to provide an early feedback about the capabilities of this package.

**Comment by danyc** [comment]
![gulp-protractor-cucumber-html-report](https://cloud.githubusercontent.com/assets/3902324/16930002/00f575c6-4d43-11e6-85fd-bcfeea694007.png)

**Comment by danyc** [comment]
Fixed in 0.1.2
