### ISSUE TITLE
protractorReport is not defined error.

### ISSUE THREAD

**Issue by JimLynchCodes** [mrooding/gulp-protractor-cucumber-html-report#15]
I follow the usage docs by making a gulp task:

> gulp.task('cucumber-report', function () {
>   gulp.src('features/reports/cucumber_report.html.json')
>     .pipe(protractorReport({
>       dest: 'reports/'
>     }));
> });

And then I run this task through the command line: 
`gulp cucumber-report`

But it gives this error:
`ReferenceError: protractorReport is not defined`

What is "protractorReport" supposed to be? I thought this module was supposed to allow me to point to the output json file from cucumberjs and then it generates a nice html file. Is that true?

**Comment by JimLynchCodes** [comment]
Anyone else seeing this error or know where "protractorReport" is coming from?

**Comment by JimLynchCodes** [comment]
For anyone who's interested:

Since this seems to be a dead project I've switched to this other one:
[](https://www.npmjs.com/package/cucumber-html-reporter)

**Comment by mrooding** [comment]
Hi @JimTheMan 

I don't have a lot of time to invest into this project anymore so if there's an alternative that's well maintained it would be a good idea to use that one. You mentioned switching to a different project but forgot to mention the name. Which project were you referring to?
