### ISSUE TITLE
will there be a PR back to robhil/grunt-protractor-cucumber-html-report?

### ISSUE THREAD

**Issue by Pyrolistical** [mrooding/gulp-protractor-cucumber-html-report#3]

**Comment by mrooding** [comment]
Unfortunately getting this to work with gulp required a lot of gulp specific refactoring. The only thing I could PR back to the original plugin would be changes done to the HTML report itself. At this time, however, there was only a single bug fix done there. 

I do have plans to add extra features to the HTML report when I find some free time. If those are done, I'm of course willing to PR those back.
